version: '3.2'

services:
  xadmin-server:
    container_name: xadmin-server
    restart: always
    image: 'xadmin-server'
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /data/xadmin-server
    volumes:
      - ./:/data/xadmin-server
    external_links:
        - mariadb:mariadb 
        - redis:redis
#    extra_hosts:
#      - "mariadb:172.31.32.1"
    sysctls:
        - net.core.somaxconn=4096
    ports:
        - 8896:8896

