# Generated by Django 5.2.7 on 2025-11-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaptchaStore",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("challenge", models.CharField(max_length=32)),
                ("response", models.CharField(max_length=32)),
                ("hashkey", models.CharField(max_length=40, unique=True)),
                ("expiration", models.DateTimeField()),
            ],
        ),
    ]
