# Generated by Django 5.2.7 on 2025-10-29 03:45

from django.db import migrations

import apps.common.fields.encrypted


class Migration(migrations.Migration):

    dependencies = [
        ("virt_center", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformcredential",
            name="password",
            field=apps.common.fields.encrypted.EncryptedCharField(
                blank=True,
                help_text="vCenter/ESXi 登录密码（自动加密存储）",
                max_length=512,
                null=True,
                verbose_name="密码",
            ),
        ),
        migrations.AlterField(
            model_name="platformcredential",
            name="session_id",
            field=apps.common.fields.encrypted.EncryptedCharField(
                blank=True, help_text="当前会话 ID（自动加密存储）", max_length=512, null=True, verbose_name="会话 ID"
            ),
        ),
    ]
